language: node_js
node_js:
  - "5.5"
python:
  - "3.5"
install:
  - cd react-frontend
  - npm install
  - cd ../py-backend
  - pip install -r requirements.txt
script:
  - py.test
  - cd ../react-frontend
  - npm run test

