mongo:
  build: ./mongo
  ports:
    - 12345:27017
  hostname: mongo
  volumes:
    - ./mongo/data/db:/data/db

deptstore:
  build: ./py-backend
  ports:
    - 5000:5000
  hostname: dept
  links: 
    - mongo:mongo

frontend:
  build: ./react-frontend
  ports:
    - 3000:3000
  hostname: frontend
  links:
    - deptstore:deptstore
