mongo:
  build: ./mongo
  hostname: mongo
  volumes:
    - /opt/wg-tools-mongo-data:/data/db

depts:
  build: ./py-backend
  hostname: depts
  links: 
    - mongo:mongo

frontend:
  build: ./react-frontend
  ports:
    - 3000:3000
  hostname: frontend
  links:
    - depts:depts
